FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

ADD . /repo
WORKDIR /repo
RUN DEBIAN_FRONTEND=noninteractive ./install.sh

RUN mkdir -p /deps
RUN ldd /usr/local/bin/ngs | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'cp % /deps;'

FROM ubuntu:20.04 as package

COPY --from=builder /deps /deps
COPY --from=builder /usr/local/bin/ngs /usr/local/bin/ngs
ENV LD_LIBRARY_PATH=/deps
